spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/evaluation_service
    username: evaluation_user
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:evaluation_user}
    password: ${RABBITMQ_PASSWORD:evaluation_password}
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

evaluation:
  service:
    audience:
      outbox:
        transport: ${OUTBOX_TRANSPORT:LOG}
        kafka:
          enabled: true
        rabbitmq:
          enabled: true
